stylesheets:
  - href: '/rss.xsl'
    media: 'all'
    type: 'text/xsl'
headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
feeds:
  # your custom feeds go here:
  1tamilmv:
    channel:
      url: https://www.1tamilmv.team
      headers:
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36"
        "Cookie": "ips4_IPSSessionFront=oe57quq1u8j9hd28r1qd9rgh6t"
    selectors:
      items:
        selector: "#ipsLayout_mainArea > div:nth-child(2) > ul > li.ipsWidget.ipsWidget_horizontal.ipsBox.ipsResponsive_block.ipsResponsive_hidePhone.ipsResponsive_hideDesktop > div > ul > li"
      title:
        selector: "#ipsLayout_mainArea > div:nth-child(2) > ul > li.ipsWidget.ipsWidget_horizontal.ipsBox.ipsResponsive_block.ipsResponsive_hidePhone.ipsResponsive_hideDesktop > div > ul > li > div> h4 > span:nth-child(2) > a"
